/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import banco.dao.ContaDAO;
import banco.model.Conta;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author henry
 */
public class TelaGerenciarConta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaGerenciarConta.class.getName());

    /**
     * Creates new form TelaGerenciarConta
     */
public TelaGerenciarConta() {
    initComponents();
    setLocationRelativeTo(null);

    listarContas();
}
private void listarContas() {

    ContaDAO dao = new ContaDAO();
    List<Conta> lista = dao.listar();

    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

    modelo.setRowCount(0);

    for (Conta c : lista) {

        modelo.addRow(new Object[]{
            c.getId(),
            c.getNumero(),
            c.getAgencia(),
            c.getCliente().getNome(),
            c.getTipo(),
            c.getSaldo()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CRIAR = new javax.swing.JButton();
        EDITAR = new javax.swing.JButton();
        EXCLUIR = new javax.swing.JButton();
        VOLTAR = new javax.swing.JButton();
        VOLTa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Caladea", 1, 15)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NUMERO", "AGENCIA", "CLIENTE", "TIPO", "SALDO"
            }
        ));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 980, 640));

        CRIAR.setBackground(new java.awt.Color(0, 0, 0));
        CRIAR.setFont(new java.awt.Font("Caladea", 1, 15)); // NOI18N
        CRIAR.setForeground(new java.awt.Color(255, 255, 255));
        CRIAR.setText("NOVA CONTA");
        CRIAR.addActionListener(this::CRIARActionPerformed);
        jPanel1.add(CRIAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 210, 190, 60));

        EDITAR.setBackground(new java.awt.Color(0, 0, 0));
        EDITAR.setFont(new java.awt.Font("Caladea", 1, 15)); // NOI18N
        EDITAR.setForeground(new java.awt.Color(255, 255, 255));
        EDITAR.setText("EDITAR CONTA");
        EDITAR.addActionListener(this::EDITARActionPerformed);
        jPanel1.add(EDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 360, 190, 60));

        EXCLUIR.setBackground(new java.awt.Color(0, 0, 0));
        EXCLUIR.setFont(new java.awt.Font("Caladea", 1, 15)); // NOI18N
        EXCLUIR.setForeground(new java.awt.Color(255, 255, 255));
        EXCLUIR.setText("EXCLUIR CONTA");
        EXCLUIR.addActionListener(this::EXCLUIRActionPerformed);
        jPanel1.add(EXCLUIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 510, 190, 60));

        VOLTAR.setBackground(new java.awt.Color(0, 0, 0));
        VOLTAR.setFont(new java.awt.Font("Caladea", 1, 15)); // NOI18N
        VOLTAR.setForeground(new java.awt.Color(255, 255, 255));
        VOLTAR.setText("VOLTAR");
        VOLTAR.addActionListener(this::VOLTARActionPerformed);
        jPanel1.add(VOLTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 660, 190, 60));

        VOLTa.setBackground(new java.awt.Color(0, 0, 0));
        VOLTa.setFont(new java.awt.Font("Caladea", 1, 24)); // NOI18N
        VOLTa.setForeground(new java.awt.Color(255, 255, 255));
        VOLTa.setText("<");
        VOLTa.addActionListener(this::VOLTaActionPerformed);
        jPanel1.add(VOLTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/henry/NetBeansProjects/Banco/src/main/java/ui/img/GConta.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1400, 970));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CRIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRIARActionPerformed
   TelaCadastroContaPoupanca tela = new TelaCadastroContaPoupanca();
    tela.setVisible(true);
    dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_CRIARActionPerformed

    private void EXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIRActionPerformed
    int linha = jTable1.getSelectedRow();

    if(linha == -1){
        return;
    }


    long id = Long.parseLong(
        jTable1.getValueAt(linha,0).toString()
    );


    ContaDAO dao = new ContaDAO();

    dao.excluir(id);


    listarContas();
    // TODO add your handling code here:
    }//GEN-LAST:event_EXCLUIRActionPerformed

    private void EDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARActionPerformed
    int linha = jTable1.getSelectedRow();

    if (linha == -1) {
        return;
    }

    long id = Long.parseLong(
        jTable1.getValueAt(linha, 0).toString()
    );

    ContaDAO dao = new ContaDAO();

    Conta conta = dao.buscarPorId(id);


    TelaCadastroContaPoupanca tela =
        new TelaCadastroContaPoupanca(conta);

    tela.setVisible(true);

    dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_EDITARActionPerformed

    private void VOLTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTaActionPerformed
    
    TelaMenuPrincipal tela = new TelaMenuPrincipal();
    tela.setVisible(true);
    dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_VOLTaActionPerformed

    private void VOLTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTARActionPerformed
    
    TelaMenuPrincipal tela = new TelaMenuPrincipal();
    tela.setVisible(true);
    dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_VOLTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaGerenciarConta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CRIAR;
    private javax.swing.JButton EDITAR;
    private javax.swing.JButton EXCLUIR;
    private javax.swing.JButton VOLTAR;
    private javax.swing.JButton VOLTa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
